# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='music_info',
            fields=[
                ('id', models.AutoField(db_column='music_id', max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='music_name', max_length=255)),
                ('singer', models.CharField(db_column='singer', max_length=255)),
                ('came_from', models.CharField(blank=True, db_column='came_from', max_length=255)),
                ('kbps', models.CharField(blank=True, db_column='music_kbps', max_length=255)),
                ('size', models.CharField(blank=True, db_column='music_size', max_length=255)),
                ('language', models.CharField(blank=True, db_column='music_language', max_length=255)),
                ('released_data', models.CharField(blank=True, db_column='released_data', max_length=255)),
                ('url', models.CharField(db_column='bdyun_url', max_length=255)),
                ('password', models.CharField(blank=True, db_column='bdyun_password', max_length=255)),
            ],
        ),
    ]
