# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-07 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='music_info',
            new_name='Music',
        ),
        migrations.AlterModelTable(
            name='music',
            table='music_info',
        ),
    ]
